apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  labels:
    app: db-pod
spec:
  storageClassName: db-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi